# Generated by Django 4.0.4 on 2022-05-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_num', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('singer', models.CharField(max_length=50)),
                ('loacation', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
