# Generated by Django 4.0.4 on 2022-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_title',
            field=models.CharField(max_length=100),
        ),
    ]
