# Generated by Django 4.0.4 on 2022-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='senti1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='senti2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='senti3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='senti4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='senti5',
            field=models.IntegerField(),
        ),
    ]
