# Generated by Django 4.0.4 on 2022-05-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_musicmusic_playlistplaylist_delete_playlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmusic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlistplaylist',
            options={},
        ),
    ]
