# Generated by Django 4.0.4 on 2022-05-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_music_playlist_delete_usermusic_delete_userplaylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
