# Generated by Django 4.0.4 on 2022-05-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMusic',
            fields=[
                ('music_num', models.IntegerField(primary_key=True, serialize=False)),
                ('music_title', models.CharField(max_length=100)),
                ('music_singer', models.TextField()),
                ('music_lyrics', models.TextField()),
                ('music_nation', models.TextField()),
                ('music_path', models.TextField()),
                ('image_path', models.TextField()),
                ('youtube_path', models.TextField()),
                ('senti1', models.IntegerField()),
                ('senti2', models.IntegerField()),
                ('senti3', models.IntegerField()),
                ('senti4', models.IntegerField()),
                ('senti5', models.IntegerField()),
                ('music_genre', models.TextField()),
            ],
            options={
                'db_table': 'music_music',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistPlaylist',
            fields=[
                ('playlist_num', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.TextField()),
                ('music_num', models.TextField()),
                ('playlist_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'playlist_playlist',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
